### ISSUE TITLE
Add eth64 support

### ISSUE THREAD

**Issue by todofixthis** [ethereumjs/ethereumjs-devp2p#55]
From [Ethereum Wire Protocol documentation](https://github.com/ethereum/devp2p/blob/master/caps/eth.md#eth64-eip-2364-november-2019):

> ### eth/64 ([EIP-2364], November 2019)
> 
> Version 64 changed the Status message to include the [EIP-2124] ForkID. This allows peers
to determine mutual compatibility of chain execution rules without synchronizing the
blockchain.
> 
> [EIP-2124]: https://eips.ethereum.org/EIPS/eip-2124

Supporting eth64 would remove the need to fork-verify new peers and reduce the complexity of application code.

**Comment by holgerd77** [comment]
Yes, this would be very beneficial to have, have added some labelling including a "very important" priority categorization. Communication noise respectively the level of communication with not useful clients on the library/protocol is still pretty substantial, and this would already help significantly.

**Comment by holgerd77** [comment]
Some more context: [EIP-2124](https://eips.ethereum.org/EIPS/eip-2124) is a general description on the fork identifier, on top [EIP-2364](https://eips.ethereum.org/EIPS/eip-2364) describes an extended protocol handshake for `eth/64`.

**Comment by holgerd77** [comment]
I am currently trying to recreate the `forkhash` values from the [EIP](https://eips.ethereum.org/EIPS/eip-2124) (see "Specification").

I have managed to get `forkhash0` but having a hard time to get any further (`forkhash1`), this is what I've got so far:

```typescript
const CRC32 = require('crc-32') // Using https://www.npmjs.com/package/crc-32
const genesis = Buffer.from('d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3', 'hex') // mainnet genesis
let inputBuffer
inputBuffer = Buffer.concat([ genesis ])
// CRC32 deliver result as signed 32-bit integer,
// this is what I got from the internet [tm] for conversion
forkhash = new Number(CRC32.buf(inputBuffer) >>> 0).toString(16) // 'fc64ec04', works

// Now to the UInt64 part for the block number
// Follows solution from https://stackoverflow.com/a/14731148
// (also tried more naive approaches, didn't work either)
let blockNumHomestead = 1150000
let blockNumHomesteadHex = 0x118c30
let b = Buffer.alloc(8)
b.writeUInt32BE(blockNumHomesteadHex >> 8, 0)
b.writeUInt32BE(blockNumHomesteadHex & 0x00ff, 4) // <Buffer 00 00 11 8c 00 00 00 30>
inputBuffer = Buffer.concat([ genesis, b ])
forkhash = new Number(CRC32.buf(inputBuffer) >>> 0).toString(16) // 'a18c51e1' -> wrong!

// More naive approach
let b2 = Buffer.from('118c30', 'hex')
inputBuffer = Buffer.concat([ genesis, b2 ])
forkhash = new Number(CRC32.buf(inputBuffer) >>> 0).toString(16) // 'ec57463f' -> also wrong!
```

Any recommendations on this respectively hints on what I am doing wrong (respectively also what could eventually be done easier?). Still floating a bit on all the buffer conversion and byte manipulation stuff and spent the whole morning on this. 😕

//cc @s1na @cgewecke (others as well of course!)

**Comment by s1na** [comment]
I'd just hardcode a 64bit version of the block number in the more naive approach like this:

```
let b2 = Buffer.from('0000000000118c30', 'hex')
```

**Comment by holgerd77** [comment]
Ok, here is a first suggestion for an implementation which tries to balance between the requirements and constraints from the specification and the structure of our current library setup together with the intended scope of the libraries.

Feedback very welcome!

## ethereumjs-common

The [common](https://github.com/ethereumjs/ethereumjs-vm/tree/master/packages/common) library gets two new public API methods in [index.ts](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/common/src/index.ts):

```javascript
common.forkHashes(): Dictionary
```

This returns a dictionary with the fork hashes as key and the block numbers of the next HF (`FORK_NEXT`) as values:

```javascript
const forkHashes = {
  FH0: 1150,
  FH1: 26950,
  FH3: 596839,
  FH4: 0
}
```

Second API method returns the fork hash from the given or provided hardfork:

```javascript
common.forkHash(hardfork?: string): string
```

Since fork hashes are static and it is unnecessary and costly to recalc on every run we can include these into the `chain` files for the supported chains:

```javascript
{
  "name": "constantinople",
  "block": 7280000,
  "forkhash": "0x668db0af"
}
```

Fork hash field should be optional though to not make this a limitation for custom chains with custom/simple chain files where people might not want or not be able to calculate the fork hashes.

Therefore we provide an additiona internal method providing the hash calculation (roughly the CRC32 algorithm/code from above):

```javascript
common._calcForkHash(hardfork)
```

Both `common.forkHashes()` and `common.forkHash()` first try to access the static field in the chain files and otherwise fall back to calculation. `common._calcForkHash()` can additionally be used for the tests to run a hash calculation for all supported chains and forks and compare against the static values.

## ethereumjs-devp2p

Pre-note: one design goal for the devp2p library was (after some reflectional back-and-forth) to not have  to introduce a `Common` library dependency here, since this would likely be too opinionated and not play well with the concurrent nature of the library.  

### RLPx

The RLPx class gets a new [option](https://github.com/ethereumjs/ethereumjs-devp2p/blob/master/src/rlpx/rlpx.ts#L17) to pass in the static `forkHashes` dictionary created by the `Common` class.

### ETH

If I read the code correcly the current `ETH` implementation [refuses](https://github.com/ethereumjs/ethereumjs-devp2p/blob/master/src/eth/index.ts#L84) incoming `status` messages without an own `status` send before anyhow, so this case is not a problem for now and we only have to handle `ETH.sendStatus()`

There I would suggest the following additions:

The `Status` type gets extended, then we have the `forkHash` available:

```typescript
export type Status = {
    version: number
    networkId: number
    td: Buffer
    bestHash: Buffer
    genesisHash: Buffer,
    forkHash: Buffer
  }
```

The `Eth.sendStatus()` message gets an optional parameter `head`:

```javascript
Eth.sendStatus(status, head?)
```

The `ETH` protocol instance should then hopefully have all the information (together with the `forkHashes` dict from the `RLPx` instance passed on) to do follow the validation rules from the [specification](https://eips.ethereum.org/EIPS/eip-2124) (needs some evaluation though).

If a `head` is not provided to `Eth.sendStatus()` we take the block height associated with the `forkHash` status field from the `forkHashes` dictionary instead.

---

So far, maybe play this through with the validation rules from the specification to see if the suggested structure holds. I am roughly 70-80% certain here. 😄

**Comment by evertonfraga** [comment]
Super interesting content!
